services:
  redis:
    image: redis:redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - redis-network
    environment:
      - REDIS_PASSWORD=Gumon#2024
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

networks:
  redis-network:
    driver: bridge
