services:
  redis:
    image: redis:redis:7.2-alpine
    container_name: my_redis
    ports:
      - "6379:6379"
    networks:
      - redis-network
    environment:
      - REDIS_PASSWORD=Gumon#2024
    command: [ "redis-server", "--requirepass", "Gumon#2024" ]

networks:
  redis-network:
    driver: bridge
